In [1]:
import numpy as np

In [51]:
print("-"*60)
print("ARRAY CREATION")
print("-"*60)

arr = np.array([1,2,3,4])  # 1-D Array
print(arr)

print()

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2-D Array or Matrix
print(matrix)

------------------------------------------------------------
ARRAY CREATION
------------------------------------------------------------
[1 2 3 4]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
print("-"*60)
print("ARRAY GENERATION FUNCTION")
print("-"*60)

sequence = np.arange(1,11)
print(sequence)

print()

zeroMatrix = np.zeros((4,2))       # single or 1-d zero zeros(6)
print(zeroMatrix)

print()

oneMatrix = np.ones((4,3))
print(oneMatrix)

print()

sameSpace = np.linspace(1,10,9)   # 9 -> no of element between 1 to 10 with same differnce
print(sameSpace)

print()


------------------------------------------------------------
ARRAY GENERATION FUNCTION
------------------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]



In [49]:
print("-"*60)
print("RANDOM GENERATION FUNCTION")
print("-"*60)

# RANDOM IS A LIBRARY IN PYTHON THAT WILL GENERATE RANDOM FUNCTION

random1 = np.random.rand(5)   # rand() -> conatins values from -1 to 1 only called NORMALIZATION
print(random1)

print()

random1 = np.random.randn(5)   # randn() -> conatins values from -3 to 3 only called STANDARIZATION
print(random1)

print()

randNumOne = np.random.randint(10)   # from 0 to 10 only 1 random number will be generate
print(randNumOne)

print()

randNumMultiple = np.random.randint(10,30,6) # from 10 t0 30 i want 6 random number in the form of array
print(randNumMultiple)

print()

------------------------------------------------------------
RANDOM GENERATION FUNCTION
------------------------------------------------------------
[0.85414563 0.88774438 0.06446197 0.72770368 0.72397526]

[-1.07932566  0.54354756  0.36187745  1.58398068  0.01502795]

4

[19 15 13 11 15 19]



In [77]:
import numpy as np

# Create a 3x3 NumPy array
rowXcol = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Display the array
print(rowXcol)


# ---------------- ARRAY ATTRIBUTES ----------------

# Shape -> (rows, columns)
print(rowXcol.shape)

# Size -> total number of elements
print(rowXcol.size)

# Data type of elements
print(rowXcol.dtype)


# ---------------- BASIC OPERATIONS ----------------

# Minimum value in array
print(rowXcol.min())

# Maximum value in array
print(rowXcol.max())

# Sum of all elements
print(rowXcol.sum())


# ---------------- AXIS OPERATIONS ----------------

# Column-wise sum (axis=0)
print(np.sum(rowXcol, axis=0))

# Row-wise sum (axis=1)
print(np.sum(rowXcol, axis=1))


# ---------------- STATISTICS ----------------

# Mean (average)
print(rowXcol.mean())

# Standard deviation
print(rowXcol.std())


# ---------------- INDEX OPERATIONS ----------------

# Index of maximum value (flattened array index)
print(rowXcol.argmax())

# Index of minimum value (flattened array index)
print(rowXcol.argmin())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
1
9
45
[12 15 18]
[ 6 15 24]
5.0
2.581988897471611
8
0


In [76]:
print("-"*60)
print("RESHAPING & RESIZING") 
print("-"*60)

arr = np.arange(1,21)
print(arr)

print()

matrixArr = arr.reshape(5,4)   # reshape used to convert array dimmenssions
print(matrixArr)

print()



------------------------------------------------------------
RESHAPING & RESIZING
------------------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]

