In [15]:
print("-"*60)
print("INDEXING & SLICING OF VECTORS") 
print("-"*60)

import numpy as np

arr = np.arange(11,21)
print(arr)
print()
print(arr[5])

# SLICING[start,end,step]
print()
print(arr[2:6])
print()
print(arr[2:8:2])
print()



------------------------------------------------------------
INDEXING & SLICING OF VECTORS
------------------------------------------------------------
[11 12 13 14 15 16 17 18 19 20]

16

[13 14 15 16]

[13 15 17]


In [32]:
print("-"*60)
print("INDEXING & SLICING OF MATRIX")
print("-"*60)

# Create 5x6 matrix
matrix = np.arange(1, 31).reshape(5, 6)
print(matrix)
print()

# Access 4th row (index 3)
print(matrix[3])
print()

# Access entire 1st column (index 0)
print(matrix[:, 0])   # 👉 THIS IS COLUMN 1
print()

# Access element at row 0, column 0
print(matrix[0, 0])
print()

# SLICING [starting row : ending row , starting column : ending column]
print(matrix[0:2,1:3])
print()

------------------------------------------------------------
INDEXING & SLICING OF MATRIX
------------------------------------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

[19 20 21 22 23 24]

[ 1  7 13 19 25]

1

[[2 3]
 [8 9]]



In [38]:
print("-"*60)
print("BOOLEAN INDEXING")
print("-"*60)

arr = np.arange(11,21)
print(arr)
print()

# MAKE ARRAY ONLY EVEN 
bool_index = arr % 2 == 0
print(bool_index)
arr = arr[bool_index]
print(arr)



------------------------------------------------------------
BOOLEAN INDEXING
------------------------------------------------------------
[11 12 13 14 15 16 17 18 19 20]

[False  True False  True False  True False  True False  True]
[12 14 16 18 20]
