In [8]:
print("-"*60)
print("ARITHMETIC OPERATIONS -> SIZE MUST BE SAME OF BOTH ARRAY")
print("-"*60)

import numpy as np  # Import NumPy

# Create arrays
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Array a:", a)
print("Array b:", b)
print()

# Element-wise operations
print("Addition:", a + b)        # Adds corresponding elements
print("Subtraction:", a - b)     # Subtracts corresponding elements
print("Multiplication:", a * b)  # Multiplies corresponding elements
print("Division:", a / b)        # Divides corresponding elements
print("Power:", a ** 2)          # Squares each element of a

------------------------------------------------------------
ARITHMETIC OPERATIONS -> SIZE MUST BE SAME OF BOTH ARRAY
------------------------------------------------------------
Array a: [10 20 30]
Array b: [1 2 3]

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]
Power: [100 400 900]


In [10]:
print("-"*60)
print("BROADCASTING")
print("-"*60)

import numpy as np

# 1D array
a = np.array([1, 2, 3])

# Scalar value
b = 10

print("Array:", a)
print("Scalar:", b)
print()

# Broadcasting: scalar is added to each element
print("Array + Scalar:", a + b)

# 2D array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("\nMatrix:\n", matrix)

# Broadcasting: row-wise addition
print("\nMatrix + Array:\n", matrix + a)

------------------------------------------------------------
BROADCASTING
------------------------------------------------------------
Array: [1 2 3]
Scalar: 10

Array + Scalar: [11 12 13]

Matrix:
 [[1 2 3]
 [4 5 6]]

Matrix + Array:
 [[2 4 6]
 [5 7 9]]


In [4]:
print("-"*60)
print("DEEP COPY vs SHALLOW COPY")
print("-"*60)

import numpy as np

a = np.array([1, 2, 3])

# Shallow copy (linked to original)
b = a.view()
b[0] = 100  # Changing b also changes a

print("After Shallow Copy Change:")
print("Original a:", a)
print("Shallow b:", b)
print()

# Deep copy (independent copy)
c = a.copy()
c[1] = 200  # Changing c does NOT affect a

print("After Deep Copy Change:")
print("Original a:", a)
print("Deep c:", c)

------------------------------------------------------------
DEEP COPY vs SHALLOW COPY
------------------------------------------------------------
After Shallow Copy Change:
Original a: [100   2   3]
Shallow b: [100   2   3]

After Deep Copy Change:
Original a: [100   2   3]
Deep c: [100 200   3]


In [12]:
print("-"*60)
print("MATRIX OPERATIONS")
print("-"*60)

import numpy as np

# Define matrices
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print()

# Matrix operations
print("Addition:\n", A + B)              # Element-wise addition
print("Multiplication (Dot Product):\n", A @ B ) # Matrix multiplication or np.dot(A,B)
print("Transpose of A:\n", A.T)          # Rows -> Columns
print("Determinant of A:", np.linalg.det(A))  # Scalar value

------------------------------------------------------------
MATRIX OPERATIONS
------------------------------------------------------------
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Addition:
 [[ 6  8]
 [10 12]]
Multiplication (Dot Product):
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Determinant of A: -2.0000000000000004


In [6]:
print("-"*60)
print("STACKING ARRAYS")
print("-"*60)

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Array a:", a)
print("Array b:", b)
print()

# Horizontal stacking (side by side)
print("Horizontal Stack:", np.hstack((a, b)))

# Vertical stacking (one above another)
print("Vertical Stack:\n", np.vstack((a, b)))

------------------------------------------------------------
STACKING ARRAYS
------------------------------------------------------------
Array a: [1 2 3]
Array b: [4 5 6]

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [7]:
print("-"*60)
print("SPLITTING ARRAYS")
print("-"*60)

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

print("Original Array:", a)

# Split into equal parts
print("Split into 3 parts:", np.split(a, 3))   # hsplit or vsplit are also present
print()

# 2D array
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])

print("Matrix:\n", matrix)

# Horizontal split (column-wise)
print("\nHorizontal Split:\n", np.hsplit(matrix, 2))

# Vertical split (row-wise)
print("\nVertical Split:\n", np.vsplit(matrix, 2))

------------------------------------------------------------
SPLITTING ARRAYS
------------------------------------------------------------
Original Array: [1 2 3 4 5 6]
Split into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]

Matrix:
 [[1 2 3 4]
 [5 6 7 8]]

Horizontal Split:
 [array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]

Vertical Split:
 [array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
